defaults:
  form_path: '/rails-girls-krakow-2016'
  registration:
    from: 13.02.2016
    to: 2.05.2016
  reviewers:
    - lesniakania
    - basiam
    - szemek
    - gitjul
    - szynszyliszys
    - ewelinawilkosz
    - burakukula
    - dalach
    - heypiotr
    - katmarii
    - bivanitz
