defaults:
  form_path: '/rails-girls-krakow-2016'
  registration:
    from: 06.03.2016
    to: 02.04.2016
  reviewers:
    - lesniakania
    - informatykgosia
    - basiam
    - rusilko
    - gitjul
    - szynszyliszys
    - dalach
    - katmarii
    - balontomasz
